---
# tasks file for ec2-1

- name: Add the user 'docker', appending the group 'admins' and 'users' to the user's groups
  user:
    name: docker
    groups: users
    append: yes
  become: yes


- name: Check If Python Is Installed
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  become: yes

- name: Make Sure Docker Is Installed
  become: yes
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Start Docker Service
  become: yes
  service:
    name: docker
    state: started

- name: Clone Git Repository
  git:
    repo: https://github.com/dvdgitman/ip-geolocation-locator
    dest: /home/ubuntu/ip/iplocation

- name: make sure docker-py installed
  become: yes
  pip:
    name: docker-py

- name: Log into DockerHub
  become: yes
  docker_login:
    username: "davidgman2"
    password: "123456789"
    api_version: auto

- name: Build an image and push to docker hub
  become: yes
  docker_image:
    build:
      path: /home/ubuntu/ip/iplocation
    name: ip:v1.0
    repository: davidgman2/ip
    pull: false
    source: build