---
# tasks file for test-role-1
# first instance

- name: EC2
  become: yes
  hosts: hosts
  vars_files:
    - pass.yml
  tasks:
    - name: Create Instance
      ec2:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        key_name: ansible
        instance_type: t2.micro
        image: ami-0a91cd140a1fc148a
        region: us-east-2
        wait: yes
        group: MySecurityGroup
        count: 1
        vpc_subnet_id: subnet-d34b319f
        assign_public_ip: yes
        instance_tags:
          Name: First EC2

    - name: Make Sure Docker Is Installed
      apt:
        name: docker.io
        state: present
        update_cache: yes
      become: yes

    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Clone Git Repository
      git:
        repo: https://github.com/dvdgitman/ip-geolocation-locator
        dest: /home/ubuntu/ip/iplocation

    - name: Log into DockerHub
      docker_login:
        username: davidgman2
        password: 123456789

    - name: Build an image and push to docker hub
      docker_image:
        build:
          path: /home/ubuntu/ip/iplocation:1.1
        name: ip
        repository: davidgman2/ip
        tag: v1
        source: build
