---
# tasks file for ec-1
# first instance

- name: EC2
  become: yes
  hosts: localhost
  vars_files:
    - pass.yml
  tasks:
    - name: Make Sure Boto Is Installed
      pip:
        name: boto
        state: present

    - name: Make Sure Boto3 Is Installed
      pip:
          name: boto3
          state: present

    - name: Make Sure Docker py Is Installed
      pip:
          name: docker-py
          state: present

    - name: Creating Security Group for EC2 on AWS
      ec2_group:
        name: MySecurityGroup
        description: Security Group for EC2 allowing port for http and ssh
        region: us-east-2
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        rules:
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 80
             to_port: 80
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 8080
             to_port: 8080
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 443
             to_port: 443
             cidr_ip: 0.0.0.0/0
        rules_egress:
           - proto: all
             cidr_ip: 0.0.0.0/0

    - name: Create First Instance
      ec2:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        key_name: ansible
        instance_type: t2.micro
        image: ami-0a91cd140a1fc148a
        region: us-east-2
        wait: yes
        group: MySecurityGroup
        count: 1
        vpc_subnet_id: subnet-d34b319f
        assign_public_ip: yes
        instance_tags:
          Name: First EC2

      register: ec2

    - name: Create Second Instance
      ec2:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        key_name: ansible
        instance_type: t2.micro
        image: ami-0a91cd140a1fc148a
        region: us-east-2
        wait: yes
        group: MySecurityGroup
        count: 1
        vpc_subnet_id: subnet-d34b319f
        assign_public_ip: yes
        instance_tags:
          Name: Second EC2

      register: ec21

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: firstec2
      loop: "{{ ec2.instances }}"

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: firstec21
      loop: "{{ ec21.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        state: started
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        state: started
      loop: "{{ ec21.instances }}"

- hosts: firstec2
  gather_facts: no
  tasks:
  - name: running role
    include_role:
      name: ec2-1

- hosts: firstec21
  gather_facts: no
  tasks:
  - name: running role
    include_role:
      name: ec2-2
