---
# tasks file for ec2-2
- name: Make Sure Docker Is Installed
  become: yes
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Start Docker Service
  become: yes
  service:
    name: docker
    state: started



