---
# tasks file for ec2-2
- name: Check If Python Is Installed
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  become: yes

- name: Make Sure Docker Is Installed
  become: yes
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Start Docker Service
  become: yes
  service:
    name: docker
    state: started

- name: make sure docker-py installed
  become: yes
  pip:
    name: docker-py

- name: pull a Docker Image
  become: yes
  docker_image:
    name: int2020devops/ansible:v0.1